# Generated by Django 4.2.7 on 2023-11-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(max_length=125, on_delete=django.db.models.deletion.CASCADE, to='todolist.author'),
        ),
    ]
