# Generated by Django 4.2.7 on 2023-11-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_book_author_alter_book_publication_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
